export enum Track {
    BAHRAIN, SAUDI_ARABIA, AUSTRALIA, IMOLA, MIAMI, SPAIN, MONACO, AZERBAIJAN, CANADA,
    SILVERSTONE, AUSTRIA, FRANCE, HUNGARY, BELGIUM, ZANDVOORT, MONZA, RUSSIA, MARINA_BAY, JAPAN, USA, MEXICO, BRAZIL, ABU_DHABI
}